org.gradle.jvmargs=-Xmx1024m -Xss512k -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=64m -XX:ActiveProcessorCount=2 -XX:HeapBaseMinAddress=8g -XX:+HeapDumpOnOutOfMemoryError
org.gradle.workers.max=1
org.gradle.parallel=false
android.useAndroidX=true
android.nonFinalResIds=false
android.enableJetifier=true
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
